#!/usr/bin/env bash

export NODE_ENV=development
# CLIENT_PORT=$(node ./scripts/find-open-port.js)
# export NODE_TLS_REJECT_UNAUTHORIZED='0'

# exec nodemon \
#   -w ./server \
#   -w ./scripts/ \
#   -w ./env.js \
#   --exec ./scripts/start.cjs

exec dotenv -e .env -- concurrently \
  --names "server,client" \
  "nodemon -w server --exec ./scripts/start.cjs" \
  "cd client && npm run dev"
